CSResults/Models/Module.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;

namespace CSResults.Models
{
    public class Module
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [DisplayName("Module ID")]
        public string moduleID { get; set; }

        [DisplayName("Module Name")]
        public string moduleName { get; set; }

        public virtual ICollection<Result> Results { get; set; }
    }
}

CSResults/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CSResults.DAL;
using CSResults.Models;

namespace CSResults.Controllers
{
    public class ModuleController : Controller
    {
        private ModuleContext db = new ModuleContext();

        // GET: Module
        public ActionResult Index()
        {
            return View(db.Module.ToList());
        }

        // GET: Module/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = db.Module.Find(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // GET: Module/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Module/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "moduleID,moduleName")] Module module)
        {
            if (ModelState.IsValid)
            {
                db.Module.Add(module);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(module);
        }

        // GET: Module/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = db.Module.Find(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // POST: Module/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "moduleID,moduleName")] Module module)
        {
            if (ModelState.IsValid)
            {
                db.Entry(module).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(module);
        }

        // GET: Module/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = db.Module.Find(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // POST: Module/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Module module = db.Module.Find(id);
            db.Module.Remove(module);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CSResults/Controllers/ModulesController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using CSResults.DAL;
using CSResults.Models;

namespace CSResults.Controllers
{
    public class ModulesController : Controller
    {
        private ModuleContext db = new ModuleContext();

        public ActionResult Index()
        {

            List<Module> moduleLst = db.Module.ToList();
            List<Result> resultLst = db.Result.ToList();

            //Get all the module and results data
            var modRes = from m in moduleLst
                         join r in resultLst on m.moduleID equals r.modID
                         orderby m.moduleName,r.year descending
                         select new ResultsViewModel { module = m, result = r };

            return View(modRes);
        }

        public ActionResult Graph()
        {
            List<Module> moduleLst = db.Module.ToList();
            List<Result> resultLst = db.Result.ToList();


            var modRes = from m in moduleLst
                         join r in resultLst on m.moduleID equals r.modID
                         where m.moduleName == "Introduction to Software Development"
                         select new ResultsViewModel { module = m, result = r };

            //Save all modules names and the filtered module data to the ResultsGraphViewModel
            var graphData = new ResultsGraphViewModel
            {
                modules = moduleLst.OrderBy(m => m.moduleName),
                resultViewModel = modRes
            };

            return View(graphData);
        }

      [HttpPost]
        public ActionResult Test(ResultsGraphViewModel res)
        {
            
            List<Module> moduleLst = db.Module.ToList();
            List<Result> resultLst = db.Result.ToList();


            var modRes = from m in moduleLst
                         join r in resultLst on m.moduleID equals r.modID
                         where m.moduleID == res.moduleID
                         select new ResultsViewModel { module = m, result = r };

            //Save all modules names and the filtered module data to the ResultsGraphViewModel
            var graphData = new ResultsGraphViewModel
            {
                modules = moduleLst.OrderBy(m => m.moduleName),
                resultViewModel = modRes
            };

            return View(graphData);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

CSResults/Views/Modules/Graph.cshtml
@model CSResults.Models.ResultsGraphViewModel
@{
    ViewBag.Title = "Graph";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    //Data for chart
    var yrs = new List<String>();
    var mean = new List<Double?>();
    var module_name = Model.resultViewModel.First().module.moduleName.ToString();


    foreach (var item in Model.resultViewModel)
    {
        yrs.Add(item.result.year);
        mean.Add(item.result.mean);
    }
}

<h2>Graph</h2>


<div class="form-group row">

    @using (Html.BeginForm("Test", "Modules", FormMethod.Post, new { @class = "form-inline ml-2 col-11 justify-content-center" }))
    {
        <label for="module" class="pr-2 pl-2">
            @Html.DisplayNameFor(model => model.moduleID)
        </label>

        @Html.DropDownListFor(model => model.moduleID,
             new SelectList(Model.modules, "moduleID", "moduleName"), new { @class = "form-control mr-2 col-lg-6 col-md-5 col-sm-4" })


        <button type="submit" class="btn btn-success">
            <i class="fa fa-search"></i>
        </button>


    }

</div>

<canvas id="lineChart"></canvas>


<script>

    var ctx = document.getElementById('lineChart').getContext('2d');
    var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'line',

    // The data for our dataset
    data: {
        labels: @Html.Raw(Json.Encode(yrs)),
        datasets: [{
            label: @Html.Raw(Json.Encode(module_name)),
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: @Html.Raw(Json.Encode(mean))
        }]
    },

    // Configuration options go here
    options: {}
});

</script>

CSResults/Views/Modules/Index.cshtml
@model IEnumerable<CSResults.Models.ResultsViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/bundles/bootstrapTable")


<script src="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.15.5/dist/extensions/fixed-columns/bootstrap-table-fixed-columns.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.15.5/dist/extensions/export/bootstrap-table-export.min.js"></script>

<h2>Results for all Modules</h2>

<br>

<table 
       id="resultsTable"
       data-toggle="table"
       data-search="true"
       data-show-columns="true"
       data-sortable="true"
       data-pagination="true"
       data-fixed-columns="true"
       data-fixed-number=2
       data-show-export="true"
       data-export-data-type="all">
    <thead>
        <tr id="title">

            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.module.moduleName)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.year)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.mean)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.median)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.below30)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.below40)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.below50)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.below60)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.below70)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.below80)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.result.above80)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="body">
                <td>
                    @Html.DisplayFor(modelItem => item.module.moduleName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.mean)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.median)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.below30)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.below40)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.below50)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.below60)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.below70)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.below80)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.result.above80)
                </td>
            </tr>


        }
    </tbody>
</table>