CSResults/Controllers/DataController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using CSResults.DAL;
using CSResults.Models;
using System.Data.Entity;

namespace CSResults.Controllers
{
    public class DataController : Controller
    {
        private IGenericRepository<Module> _module;
        private IGenericRepository<Result> _result;
        public ResultsGraphViewModel _resultsGraphViewModel;

        public DataController(IGenericRepository<Module> module , 
                                IGenericRepository<Result> result, ResultsGraphViewModel resultsGraphViewModel)
        {
            _module = module;
            _result = result;
            _resultsGraphViewModel = resultsGraphViewModel;
        }

        public ViewResult Table()
        {
            //Gets all the results
            var res = _result.GetAll(x => x.OrderBy(r => r.Module.moduleName),x => x.Module);
 
            return View(res);
        }

        public ActionResult ModuleDefault()
        {
            //Returns results for Introduction to Software Development if no option is selected
            //or when loading the page before the user is able to select an option
            var res = _result.Get(m => m.modName == "Introduction to Software Development",null, x => x.Module);

            //Save all modules names and the filtered module data to the ResultsGraphViewModel
            _resultsGraphViewModel.modules = _module.GetAll(x => x.OrderBy(r => r.moduleName));
            _resultsGraphViewModel.Result = res;

            return View("Module", _resultsGraphViewModel);
        }

        [HttpPost]
        public ActionResult Module(ResultsGraphViewModel resFilter)
        {
            //Gets the module selected by the user
            var res = _result.Get(m => m.moduleID == resFilter.moduleID, null, x => x.Module);

            //Save all modules names and the filtered module data to the ResultsGraphViewModel
            _resultsGraphViewModel.modules = _module.GetAll(x => x.OrderBy(r => r.moduleName));
            _resultsGraphViewModel.Result = res;

            return View(_resultsGraphViewModel);

        }

        [HttpGet]
        public ActionResult Module(string id)
        {
            //If no module is passed into the URL go to the default graph
            if (id == null)
            {
                return RedirectToAction("ModuleDefault");
            } 
            else
            {
                //Gets the module inputted into the URL
                var res = _result.Get(m => m.moduleID == id, null, x => x.Module);

                //Save all modules names and the filtered module data to the ResultsGraphViewModel
                _resultsGraphViewModel.modules = _module.GetAll(x => x.OrderBy(r => r.moduleName));
                _resultsGraphViewModel.Result = res;

                //If module cannot be found go to the default graph
                if (res.Count() == 0)
                {
                    return RedirectToAction("ModuleDefault");
                }

                return View(_resultsGraphViewModel);

            }

        }

    }

}

CSResults/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CS Results</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/argon")
    @Scripts.Render("~/bundles/chart")
    @Scripts.Render("~/bundles/popper")
    @Styles.Render("~/Content/css")
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">

</head>
<body>
    <!-- NavBar which contains the sidebar-->
    <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">

        <!--Toggler-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Sidebar Header -->
        <div class="sidebar-header">
            <a class="navbar-brand"> @Html.ActionLink("CS Results", "Index", "Home")</a>
        </div>

        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">

            <!--Sidebar Items-->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <i class="fa fa-table fa-fw text-blue nav-list-item" aria-hidden="true"></i> <a>@Html.ActionLink("Results Table", "Table", "Data")</a>
                </li>
                <li class="nav-item">
                    <i class="fa fa-area-chart fa-fw text-orange" aria-hidden="true"></i> <a>@Html.ActionLink("Results by Module", "ModuleDefault", "Data")</a>
                </li>
                <li class="nav-item">
                    <i class="fa fa-bar-chart fa-fw text-pink" aria-hidden="true"></i> <a>@Html.ActionLink("Results by Academic Year", "Year", "Data")</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- Main part of the page-->
    <div class="main-content">

        <!-- NavBar on the main part of the page-->
        <nav class="navbar top-row-nav sticky-top">
            <div class="nav navbar-nav mx-auto">
                <span class="top-row-nav-text">Dashboard</span>
            </div>
        </nav>
        <br />
        <div class="container col-lg-10">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Chrisateen</p>
            </footer>
        </div>
    </div>

        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>